spring:
  ########## 开启 Spring Boot 允许 Bean 重命名机制
  main:
    allow-bean-definition-overriding: true
  ########## 配置 Redis 服务信息
  redis:
    host: localhost
    port: 6379
eureka:
  ########## 配置注册中心链接地址
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
#ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000